DROP TABLE IF EXISTS  TRADES;
CREATE TABLE TRADES (
    id INT PRIMARY KEY,
    type VARCHAR(255),
    legal_entity_id VARCHAR(255)
);

DROP TABLE IF EXISTS TRADES_PROCESSING;
CREATE TABLE TRADES_PROCESSING (
    ts TIMESTAMP,
    trade_info VARCHAR(255),
    result VARCHAR(255),
    error_message VARCHAR(255)
);